#!/bin/bash
# for use in hegemon.ucsd.edu ssh
args=("$@")
GSE=${args[0]}

mkdir -p $GSE

cd $GSE

cp -Rup ~/GSEprocessing/hegemonGEOparse.py .
cp -Rup ~/GSEprocessing/gse_processing .

python3 hegemonGEOparse.py $GSE

if [ $? -ne 0 ];
then
	echo "process.py failed"
	rm hegemonGEOparse.py
	rm gse_processing
	exit
fi

rm hegemonGEOparse.py 

bash gse_processing

rm gse_processing

cd ..
