#!/bin/bash
args=("$@")
GSE=${args[0]}

mkdir -p $GSE

cd $GSE

cp -Rup ~/GSEprocessing/HegemonFiles.py .
cp -Rup ~/GSEprocessing/HomoSapiens_ENST,ProbeID,Name.txt .

python3 HegemonFiles.py $GSE

rm HomoSapiens_ENST,ProbeID,Name.txt
rm HegemonFiles.py 

cd ..
