#!/bin/bash
# for use in hegemon.ucsd.edu ssh
args=("$@")
GSE=${args[0]}

mkdir -p $GSE

cd $GSE

cp -Rup ~/GSEprocessing/HegemonGEOparse.py .
cp -Rup ~/GSEprocessing/HomoSapiens_ENST,ProbeID,Name.txt .

python3 HegemonFiles.py $GSE

rm HomoSapiens_ENST,ProbeID,Name.txt
rm HegemonGEOparse.py 

cd ..
